[package]
name = "xv"
version = "0.1.2"
authors = ["Chris Vest <mr.chrisvest@gmail.com>"]
edition = "2018"
description = "A hex viewer for the terminal, with a visual text user interface."
keywords = ["hex", "binary", "ncurses"]
categories = ["command-line-utilities", "development-tools"]
license = "Apache-2.0"
homepage = "https://chrisvest.github.io/xv/"
repository = "https://github.com/chrisvest/xv"
readme = "Readme.adoc"

[badges.travis-ci]
repository = "chrisvest/xv"

[profile.release]
overflow-checks = true
codegen-units = 1
lto = true
opt-level = 's'
panic = "abort"

[dependencies]
cursive = { version = "0.14.0", default-features = false }
unicode-width = "0.1.6"
directories = "2.0.2"
rmp-serde = "0.13.7"
serde = "1.0.99"
serde_derive = "1.0.99"
backtrace = "0.3.35"
time = "0.1.42"
#wl-clipboard-rs = "0.2.0" # Wayland clipboard integration.

[dev-dependencies]
tempfile = "3.1.0"

[features]
default = ["cursive/ncurses-backend"]
crossterm = ["cursive/crossterm-backend"]

