[package]
name = "xv"
version = "0.1.0"
authors = ["Chris Vest <mr.chrisvest@gmail.com>"]
edition = "2018"

[profile.release]
overflow-checks = true
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
clap = "2.32.0"
#cursive = "0.11.1"
cursive = { path = "../Cursive" }
unicode-width = "0.1.5"
directories = "1.0.2"
#wl-clipboard-rs = "0.2.0" # Wayland clipboard integration.

[dev-dependencies]
tempfile = "2"
