[package]
name = "xv"
version = "0.1.0"
authors = ["Chris Vest <mr.chrisvest@gmail.com>"]
edition = "2018"
description = "A hex viewer for the terminal, with a visual text user interface."
keywords = ["hex", "binary", "ncurses"]
license = "Apache-2.0"

[profile.release]
overflow-checks = true
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
clap = "2.32.0"
#cursive = "0.11.1"
cursive = { path = "../Cursive" }
unicode-width = "0.1.5"
directories = "1.0.2"
rmp-serde = "0.13.7"
serde = "1.0.89"
serde_derive = "1.0.89"
#wl-clipboard-rs = "0.2.0" # Wayland clipboard integration.

[dev-dependencies]
tempfile = "2"
