[package]
name = "xv"
version = "0.1.0"
authors = ["Chris Vest <mr.chrisvest@gmail.com>"]
edition = "2018"

[profile.release]
debug = true
overflow-checks = true
codegen-units = 1
lto = true

[dependencies]
clap = "2.32.0"
cursive = "0.11.0"
unicode-width = "0.1.5"
#wl-clipboard-rs = "0.2.0" # Wayland clipboard integration.

[dev-dependencies]
tempfile = "2"
